label_mapping:
  0: ' Acceptance   '
  1: ' Acceptance      '
  2: ' Accomplishment '
  3: ' Admiration '
  4: ' Admiration   '
  5: ' Admiration    '
  6: ' Adoration    '
  7: ' Adrenaline     '
  8: ' Adventure '
  9: ' Affection    '
  10: ' Amazement '
  11: ' Ambivalence '
  12: ' Ambivalence     '
  13: ' Amusement    '
  14: ' Amusement     '
  15: ' Anger        '
  16: ' Anticipation '
  17: ' Anticipation  '
  18: ' Anxiety   '
  19: ' Anxiety         '
  20: ' Appreciation  '
  21: ' Apprehensive '
  22: ' Arousal       '
  23: ' ArtisticBurst '
  24: ' Awe '
  25: ' Awe    '
  26: ' Awe          '
  27: ' Awe           '
  28: ' Bad '
  29: ' Betrayal '
  30: ' Betrayal      '
  31: ' Bitter       '
  32: ' Bitterness '
  33: ' Bittersweet '
  34: ' Blessed       '
  35: ' Boredom '
  36: ' Boredom         '
  37: ' Breakthrough '
  38: ' Calmness     '
  39: ' Calmness      '
  40: ' Captivation '
  41: ' Celebration '
  42: ' Celestial Wonder '
  43: ' Challenge '
  44: ' Charm '
  45: ' Colorful '
  46: ' Compassion'
  47: ' Compassion    '
  48: ' Compassionate '
  49: ' Confidence    '
  50: ' Confident '
  51: ' Confusion '
  52: ' Confusion    '
  53: ' Confusion       '
  54: ' Connection '
  55: ' Contemplation '
  56: ' Contentment '
  57: ' Contentment   '
  58: ' Coziness     '
  59: ' Creative Inspiration '
  60: ' Creativity '
  61: ' Creativity   '
  62: ' Culinary Adventure '
  63: ' CulinaryOdyssey '
  64: ' Curiosity '
  65: ' Curiosity  '
  66: ' Curiosity   '
  67: ' Curiosity     '
  68: ' Curiosity       '
  69: ' Darkness     '
  70: ' Dazzle        '
  71: ' Desolation '
  72: ' Despair '
  73: ' Despair   '
  74: ' Despair      '
  75: ' Despair         '
  76: ' Desperation '
  77: ' Determination '
  78: ' Determination   '
  79: ' Devastated '
  80: ' Disappointed '
  81: ' Disappointment '
  82: ' Disgust '
  83: ' Disgust      '
  84: ' Disgust         '
  85: ' Dismissive '
  86: ' DreamChaser   '
  87: ' Ecstasy '
  88: ' Elation   '
  89: ' Elation       '
  90: ' Elegance '
  91: ' Embarrassed '
  92: ' Emotion '
  93: ' EmotionalStorm '
  94: ' Empathetic '
  95: ' Empowerment   '
  96: ' Enchantment '
  97: ' Enchantment   '
  98: ' Energy '
  99: ' Engagement '
  100: ' Enjoyment    '
  101: ' Enthusiasm '
  102: ' Enthusiasm    '
  103: ' Envious '
  104: ' Envisioning History '
  105: ' Envy            '
  106: ' Euphoria '
  107: ' Euphoria   '
  108: ' Euphoria     '
  109: ' Euphoria      '
  110: ' Excitement '
  111: ' Excitement   '
  112: ' Excitement    '
  113: ' Exhaustion '
  114: ' Exploration '
  115: ' Fear         '
  116: ' Fearful '
  117: ' FestiveJoy    '
  118: ' Free-spirited '
  119: ' Freedom       '
  120: ' Friendship '
  121: ' Frustrated '
  122: ' Frustration '
  123: ' Frustration     '
  124: ' Fulfillment  '
  125: ' Fulfillment   '
  126: ' Grandeur '
  127: ' Grateful '
  128: ' Gratitude '
  129: ' Gratitude  '
  130: ' Gratitude   '
  131: ' Gratitude    '
  132: ' Gratitude     '
  133: ' Grief '
  134: ' Grief      '
  135: ' Grief           '
  136: ' Happiness '
  137: ' Happiness    '
  138: ' Happiness     '
  139: ' Happy '
  140: ' Harmony '
  141: ' Harmony    '
  142: ' Harmony       '
  143: ' Hate '
  144: ' Heartache '
  145: ' Heartbreak '
  146: ' Heartbreak    '
  147: ' Heartwarming '
  148: ' Helplessness '
  149: ' Helplessness    '
  150: ' Hope '
  151: ' Hope          '
  152: ' Hopeful '
  153: ' Hypnotic '
  154: ' Iconic '
  155: ' Imagination '
  156: ' Immersion '
  157: ' Indifference '
  158: ' Indifference    '
  159: ' InnerJourney  '
  160: ' Inspiration '
  161: ' Inspiration  '
  162: ' Inspiration   '
  163: ' Inspired '
  164: ' Intimidation '
  165: ' Intimidation    '
  166: ' Intrigue      '
  167: ' Isolation '
  168: ' Jealous '
  169: ' Jealousy    '
  170: ' Jealousy        '
  171: ' Journey '
  172: ' Joy '
  173: ' Joy          '
  174: ' Joy in Baking '
  175: ' JoyfulReunion '
  176: ' Kind         '
  177: ' Kindness '
  178: ' Loneliness '
  179: ' Loneliness    '
  180: ' Loneliness      '
  181: ' Loss '
  182: ' LostLove '
  183: ' Love '
  184: ' Love         '
  185: ' Marvel       '
  186: ' Melancholy '
  187: ' Melancholy      '
  188: ' Melodic       '
  189: ' Mesmerizing '
  190: ' Mindfulness   '
  191: ' Miscalculation '
  192: ' Mischievous '
  193: ' Motivation    '
  194: ' Nature''s Beauty '
  195: ' Negative  '
  196: ' Neutral '
  197: ' Neutral   '
  198: ' Nostalgia '
  199: ' Nostalgia     '
  200: ' Nostalgia      '
  201: ' Nostalgia       '
  202: ' Numbness '
  203: ' Numbness        '
  204: ' Obstacle '
  205: ' Ocean''s Freedom '
  206: ' Optimism      '
  207: ' Overjoyed     '
  208: ' Overwhelmed '
  209: ' Overwhelmed   '
  210: ' Pensive '
  211: ' Playful '
  212: ' PlayfulJoy    '
  213: ' Positive '
  214: ' Positive  '
  215: ' Positivity '
  216: ' Pressure '
  217: ' Pride '
  218: ' Pride        '
  219: ' Pride         '
  220: ' Proud '
  221: ' Radiance    '
  222: ' Radiance      '
  223: ' Reflection '
  224: ' Reflection    '
  225: ' Regret '
  226: ' Regret        '
  227: ' Regret         '
  228: ' Rejuvenation '
  229: ' Relief '
  230: ' Renewed Effort '
  231: ' Resentment      '
  232: ' Resilience '
  233: ' Resilience   '
  234: ' Reverence '
  235: ' Reverence     '
  236: ' Romance '
  237: ' Ruins      '
  238: ' Runway Creativity '
  239: ' Sad '
  240: ' Sadness      '
  241: ' Satisfaction '
  242: ' Satisfaction  '
  243: ' Serenity '
  244: ' Serenity   '
  245: ' Serenity      '
  246: ' Serenity        '
  247: ' Shame '
  248: ' Shame        '
  249: ' Solace '
  250: ' Solitude '
  251: ' Sorrow '
  252: ' Sorrow      '
  253: ' Spark        '
  254: ' Success '
  255: ' Suffering '
  256: ' Surprise '
  257: ' Surprise     '
  258: ' Surprise      '
  259: ' Suspense '
  260: ' Sympathy '
  261: ' Tenderness    '
  262: ' Thrill '
  263: ' Thrill      '
  264: ' Thrill        '
  265: ' Thrilling Journey '
  266: ' Touched '
  267: ' Tranquility '
  268: ' Triumph '
  269: ' Vibrancy '
  270: ' Whimsy        '
  271: ' Whispers of the Past '
  272: ' Winter Magic '
  273: ' Wonder '
  274: ' Wonder     '
  275: ' Wonder       '
  276: ' Wonderment    '
  277: ' Yearning '
  278: ' Zest '
